.PHONY: clean All

All:
	@echo "----------Building project:[ Maps - Debug ]----------"
	@cd "Maps" && "$(MAKE)" -f  "Maps.mk"
clean:
	@echo "----------Cleaning project:[ Maps - Debug ]----------"
	@cd "Maps" && "$(MAKE)" -f  "Maps.mk" clean
